config/routes.rb
Rails.application.routes.draw do



  get 'devices/responsive'

  resources :categories


  resources :websites do
    collection do
      get 'search'
    end
    resources :orders, only: [:new, :create] do
      collection do
        get 'search'
      end
    end
  end


  resources :projects do
    collection do
      get 'search'
    end
    resources :reviews
  end



  get 'info/why_us'
  get 'info/pricing'
  get 'info/portofolio'


  resources :blogs do
    collection do
      get 'search'
    end
  end



  get 'users/index'

  get 'search' => "users#search"



  get 'users/show'

  devise_for :users



  match 'user_root' => 'users#show', via: [:get]
  match "profile" => "users#show", :as => 'profile', via: [:get]
  match 'users/:id' => 'users#destroy', :via => :delete, as: :admin_destroy_user

  root "pages#home"

#   =======================ERRORS=======================
  %w( 404 422 500 ).each do |code|
    get code, :to => "pages#show", :code => code
  end

#   =======================ERRORS END ==================

  get 'seller' => "websites#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'all_orders' => "orders#all_order"

  get 'how_does_it_work' => "info#how_does_it_work"

  get 'what_can_i_do' => "info#what_can_i_do"



end

app/models/website.rb
class Website < ActiveRecord::Base
  if Rails.env.development?
    has_attached_file :webimg, styles: {medium: "649x476>", thumb: "100x100>"}
  else
    has_attached_file :webimg, styles: {medium: "649x476>", thumb: "100x100>"},
                      storage: :dropbox,
                      dropbox_credentials: Rails.root.join("config/dropbox.yml"),
                      path: ":style/:id_:filename"
  end

#==================================CLOUD===========================================================================
  validates_attachment :webimg, content_type: {content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]}
  validates_attachment_presence :webimg


  validates :name, :description, :price, :url, presence: true
  validates :price, numericality: {greater_than: 0}

#====================================USER===================================================================
  belongs_to :user
  belongs_to :category
  has_many :orders, dependent: :destroy

  searchkick autocomplete: ['display_name']
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:seller,:new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]
  before_action :check_admin, except: [:search,:index,:show]
  layout "info", except:[:show]
  layout "device", only:[:show]



  def search
    if params[:search].present?
       @websites = Website.search(params[:search])
    else
       @websites = Website.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
    end
  end


  def seller
    @websites = Website.where(user: current_user).order("created_at DESC")
  end
  # GET /websites
  # GET /websites.json
  def index
    if params[:category].blank?
      @websites = Website.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @websites = Website.where(category_id: @category_id).order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
    end
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)
    @website.user_id = current_user.id

    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit(:name,:category_id, :url, :description, :price,:webimg)
    end

  def check_user
    # unless (@website.user == current_user) || (current_user.manager?)
    if current_user != @website.user
      redirect_to root_url, alert: "Sorry, you can not access here it not belong to you"
    end
  end

  def check_admin
    unless current_user.admin?
      redirect_to root_url, alert: "sorry,only admin have access"
    end
  end
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/websites/_form.html.erb
<%= form_for @website, html: {multipart: true} do |f| %>
  <% if @website.errors.any? %>
    <div id="error_explanation" class="red">
      <h2><%= pluralize(@website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% @website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :webimg %><br>
      <%= f.file_field :webimg, autofocus: true, class: "form-control" %>
    </div>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

    <div class="form-group">
      <%= f.label :category_id %><br>
      <%= f.collection_select :category_id,Category.all,:id,:name,{prompt: "Choose a category"},{class: "btn btn-default dropdown-toggle"} %>
    </div>

  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.url_field :url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: "form-control" %>
  </div>
  <div>
  <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
  </div>

    <%= f.submit class:"btn btn-default" %>
  </div><br>
<% end %>

app/views/websites/devices.html.erb
<div class="devices" id="device1">
  <iframe id="iframe" src="<%= @website.url %>"
          frameborder="0" width="100%" height="600px"></iframe>
</div>

<div class="devices center" id="device2">
  <iframe id="iframe" src="<%= @website.url %>"
          frameborder="0" width="100%" height="600px" style="width: 788px;"></iframe>
</div>

<div class="devices center" id="device3">
  <iframe id="iframe" src="<%= @website.url %>"
          frameborder="0" width="100%" height="600px" style="width: 340px;"></iframe>
</div>



  <%= link_to "Buy It Now", new_website_order_path(@website), class: "btn btn-primary", data: { no_turbolink: true } %>
</p>

<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>






<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @website.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @website.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @website.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @website.price %>
  <%= link_to "Buy It Now", new_website_order_path(@website), class: "btn btn-primary", data: { no_turbolink: true } %>
</p>

<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>

app/views/websites/edit.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">


    <h1 class="thin">Editing website</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @website %> |
    <%= link_to 'Back', websites_path %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/websites/index.html.erb
<% provide(:background_color_blog,'background-blog-color') %>
<% provide(:visibility_search_blog,'hidden') %>
<% provide(:icon_color, 'green-ic') %>
<% provide(:title_page, 'Websites') %>
<% provide(:visibility_search_website,'visible') %>
<% provide(:browse_website_visibility, 'visible') %>





<!--======================dropdown list end ==========================-->
<div class="row">
  <% @websites.each do |website| %>
      <div class="col-md-3 center padding-top-blog">
        <div class="thumbnail no-border-website-list border-website-bottom">
          <%= image_tag website.webimg.url(:medium) %>
          <!--link_to image_tag(listing.image.url), listing-->
          <div class="caption">
            <h3><%= website.name %></h3>
            <p><%=number_to_currency(website.price) %></p>
            <p><%= "Sold by #{website.user.name}" %></p>
            <%= link_to "Preview #{website.name}", website, class: "btn btn-primary btn-outline btn-rounded" %>

          </div>
        </div>
      </div>
  <% end %>
</div>
<br/>
<%= will_paginate @websites, renderer: BootstrapPagination::Rails %>

<br>







<!--==============================object===================================================-->
<% if user_signed_in? && current_user.admin? %>

    <h1>Listing websites</h1>

    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th>Url</th>
        <th>Description</th>
        <th>Price</th>
        <th>Seller name</th>
        <th colspan="1"></th>
      </tr>
      </thead>

      <tbody>
      <% @websites.each do |website| %>
          <tr>
            <td><%= website.name %></td>
            <td><%= website.url %></td>
            <td><%= website.description %></td>
            <td><%= website.price %></td>
            <td><%= "Sold by #{website.user.name}" %></td>
            <td><%= link_to 'Show', website %></td>

          </tr>
      <% end %>
      </tbody>
    </table>

    <br>
    <% if user_signed_in? && current_user.admin? %>
        <%= link_to 'New Website', new_website_path %>
    <% end %>
<% end %>

app/views/websites/new.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">


    <h1 class="thin">New website</h1>

    <%= render 'form' %>

    <%= link_to 'Back', websites_path %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/websites/search.html.erb
<% if @websites.blank? %>

    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6 padding-top-blog center">
        <i class="ti-help-alt search-icon-size-and-color"></i>

        <h1 class="font-size-title thin color-degr">No result found</h1>
      </div>
      <div class="col-md-3"></div>
    </div>

<% end %>


<% provide(:background_color_blog,'background-blog-color') %>
<% provide(:visibility_search_blog,'hidden') %>
<% provide(:icon_color, 'green-ic') %>
<% provide(:title_page, 'Websites') %>
<% provide(:visibility_search_website,'visible') %>
<% provide(:browse_website_visibility, 'visible') %>





<!--======================dropdown list end ==========================-->
<div class="row">
  <% @websites.each do |website| %>
      <div class="col-md-3 center padding-top-blog">
        <div class="thumbnail no-border-website-list border-website-bottom">
          <%= image_tag website.webimg.url(:medium) %>
          <!--link_to image_tag(listing.image.url), listing-->
          <div class="caption">
            <h3><%= website.name %></h3>
            <p><%=number_to_currency(website.price) %></p>
            <p><%= "Sold by #{website.user.name}" %></p>
            <%= link_to "Preview #{website.name}", website, class: "btn btn-primary btn-outline btn-rounded" %>

          </div>
        </div>
      </div>
  <% end %>
</div>
<br/>
<%= will_paginate @websites, renderer: BootstrapPagination::Rails %>

<br>

app/views/websites/seller.html.erb
<% provide(:visibility_search_blog,'hidden') %>
<% provide(:visibility_search_website,'hidden') %>

<% if user_signed_in? && current_user.admin? %>

<!--form search beginning-->
<%= form_tag search_websites_path, method: :get do %>
    <p>
      <%= text_field_tag :search, params[:search],class: "form-control" %>
      <%= submit_tag "Search", name: nil,class: "btn btn-default" %>
    </p>
<% end %>

<!--form search-->







<!--==============================object===================================================-->

<h1 class="thin center">Listing websites</h1>

<table class="table table-striped table-hover table-bordered">
  <thead>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Url</th>
    <th>Description</th>
    <th>Price</th>
    <th>Seller name</th>
    <th>action</th>
  </tr>
  </thead>

  <tbody>
  <% @websites.each do |website| %>
      <tr>
        <td><%= image_tag website.webimg.url(:medium), class: "image-profile" %></td>
        <td><%= website.name %></td>
        <td><%= website.url %></td>
        <td><%= website.description %></td>
        <td><%= website.price %></td>
        <td><%= "Sold by #{website.user.name}" %></td>
        <td><!-- Single button -->
          <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              Action <span class="ti-arrow-circle-down"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Show', website %></li>
              <% if (user_signed_in?) && (current_user == website.user) %>
                  <li class="divider"></li>
                  <li><%= link_to 'Edit', edit_website_path(website) %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Destroy', website, method: :delete, data: {confirm: 'Are you sure?'} %></li>
              <% end %>

            </ul>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Website', new_website_path %> |
<%= link_to "New Category", new_category_path %>

<% end %>

app/views/websites/show.html.erb
<% provide(:title_page, "#{@website.name} - #{number_to_currency(@website.price)} ") %>

<div class="devices" id="device1">
  <iframe id="iframe" src=" <%= @website.url %>"
          frameborder="0" width="100%" height="600px"></iframe>
</div>

<div class="devices center" id="device2" style="display: none;">
  <iframe id="iframe" src=" <%= @website.url %>"
          frameborder="0" width="100%" height="600px" style="width: 788px;"></iframe>
</div>

<div class="devices center" id="device3" style="display: none;">
  <iframe id="iframe" src=" <%= @website.url %>"
          frameborder="0" width="100%" height="600px" style="width: 340px;"></iframe>
</div>



<% if user_signed_in? && current_user.admin? %>

    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @website.name %>
    </p>

    <p>
      <strong>Url:</strong>
      <%= @website.url %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @website.description %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @website.price %>
      <%= link_to "Buy It Now", new_website_order_path(@website), class: "btn btn-primary", data: {no_turbolink: true} %>
    </p>

    <%= link_to 'Edit', edit_website_path(@website) %> |
    <%= link_to 'Back', websites_path %>
<% end %>