config/routes.rb
Rails.application.routes.draw do



  get 'devices/responsive'

  resources :categories


  resources :websites do
    collection do
      get 'search'
    end
    resources :orders, only: [:new, :create] do
      collection do
        get 'search'
      end
    end
  end


  resources :projects do
    collection do
      get 'search'
    end
    resources :reviews
  end



  get 'info/why_us'
  get 'info/pricing'
  get 'info/portofolio'


  resources :blogs do
    collection do
      get 'search'
    end
  end



  get 'users/index'

  get 'search' => "users#search"



  get 'users/show'

  devise_for :users



  match 'user_root' => 'users#show', via: [:get]
  match "profile" => "users#show", :as => 'profile', via: [:get]
  match 'users/:id' => 'users#destroy', :via => :delete, as: :admin_destroy_user

  root "pages#home"

#   =======================ERRORS=======================
  %w( 404 422 500 ).each do |code|
    get code, :to => "pages#show", :code => code
  end

#   =======================ERRORS END ==================

  get 'seller' => "websites#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'all_orders' => "orders#all_order"

  get 'how_does_it_work' => "info#how_does_it_work"

  get 'what_can_i_do' => "info#what_can_i_do"



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blogs, dependent: :destroy
  has_many :projects, dependent: :destroy

  validates :name, presence: true,
            length: {maximum: 75}
  validates :company, length: {maximum: 75}


  # ==============================profile ====================================
  if Rails.env.development?
    has_attached_file :profileimg, styles: {medium: "50x50>", thumb: "100x100>"},
                      default_url: "https://dl.dropbox.com/s/b84a5iphbzb0l3l/img_profile.png?dl=0"
  else
    has_attached_file :profileimg, styles: {medium: "50x50>", thumb: "100x100>"},
                      default_url: "https://dl.dropbox.com/s/b84a5iphbzb0l3l/img_profile.png?dl=0",
                      storage: :dropbox,
                      dropbox_credentials: Rails.root.join("config/dropbox.yml"),
                      path: ":style/:id_:filename"
  end

  validates_attachment :profileimg, content_type: {content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]}


  # ==============================profile end ====================================

  has_many :websites, dependent: :destroy
  #==================================Purchase=======================================
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
  #=================================================================================

  # ===============================Review=========================================
  has_many :reviews, dependent: :destroy
  searchkick
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :check_user_and_manager, except: [:show]
  before_action :check_user_and_admin, only: [:destroy]

  layout "admin"

  def search
    if params[:search].present?
      @users = User.search(params[:search])
    else
      @users = User.all.order("created_at DESC")
    end
  end



  def index
    @users = User.all.order("created_at DESC")
  end

  def show
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      redirect_to root_url, notice: "User deleted."
    end
  end


  private

  def check_user_and_manager
    unless current_user.manager?
      redirect_to root_url, alert: "Sorry only manager can have access"
    end
  end

  def check_user_and_admin
    unless current_user.admin?
      redirect_to root_url, alert: "Sorry only admin can have access"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def is_company_empty(company_name)
    if company_name.blank?
       "no company name"
    else
      company_name

    end
  end
end

app/views/users/index.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <a href="#menu-toggle" class="btn btn-success btn-rounded" id="menu-toggle">Toggle Menu</a>
    <div class="row">
      <div class="col-lg-12">

        <% if user_signed_in? && current_user.manager? %>
            <!--form search beginning-->
            <%= form_tag search_path, method: :get do %>
                <br>

                <div class="row">
                  <div class="col-md-10">
                    <%= text_field_tag :search, params[:search], class: "form-control" %>
                  </div>
                  <div class="col-md-2">
                    <%= submit_tag "Search", name: nil, class: "btn btn-primary btn-lg" %>
                  </div>
                </div>

            <% end %>


            <!--form search-->


            <h1 class="thin">All Users</h1>
            <table class="table table-striped table-hover table-bordered">
              <thead>
              <tr>
                <th>profile-img</th>
                <th>User ID</th>
                <th>name</th>
                <th>company-name</th>
                <th>email</th>
                <th>date last sign in</th>
                <th>number of signin</th>
                <th>action</th>


              </tr>
              </thead>


              <tbody>
              <% @users.each do |user| %>
                  <tr>
                    <td><%= image_tag user.profileimg.url(:medium), class: "image-profile" %></td>
                    <td><%= user.id %></td>
                    <td><%= user.name %></td>
                    <td><%= user.company %></td>
                    <td><%= user.email %></td>
                    <td><%= user.last_sign_in_at %></td>
                    <td><%= user.sign_in_count %></td>



                    <td>
                      <div class="btn-group">
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                          Action <span class="ti-arrow-circle-down"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                          <li><%= link_to "Profile", profile_path %></li>
                          <% if user_signed_in? && current_user.manager? && current_user.admin? %>
                              <li class="divider"></li>
                              <li><%= link_to "Destroy", admin_destroy_user_path(user), method: :delete, data: {confirm: "You sure?"} %></li>
                          <% end %>

                        </ul>
                      </div>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
            <!--
        <% end %> end of security  -->

      </div>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">

        <h1 class="thin">All Users</h1>
        <table class="table table-striped table-hover table-bordered">
          <thead>
          <tr>
            <th>profile-img</th>
            <th>User ID</th>
            <th>name</th>
            <th>company-name</th>
            <th>email</th>
            <th>date last sign in</th>
            <th>number of signin</th>
            <th>action</th>


          </tr>
          </thead>


          <tbody>
          <% @users.each do |user| %>
              <tr>
                <td><%= image_tag user.profileimg.url(:medium), class: "image-profile" %></td>
                <td><%= user.id %></td>
                <td><%= user.name %></td>
                <td><%= user.company %></td>
                <td><%= user.email %></td>
                <td><%= user.last_sign_in_at %></td>
                <td><%= user.sign_in_count %></td>
                <% provide(:user_name, "#{user.name if user == current_user}") %>
                <% provide(:image_profile, "#{user.profileimg.url(:medium) if user == current_user}") %>


                <td>
                  <div class="btn-group">
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                      Action <span class="ti-arrow-circle-down"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                      <li><%= link_to "Profile", profile_path %></li>

                      <li class="divider"></li>
                      <li><%= link_to "Destroy", admin_destroy_user_path(user), method: :delete, data: {confirm: "You sure?"} %></li>


                    </ul>
                  </div>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <a href="#menu-toggle" class="btn btn-success btn-rounded" id="menu-toggle">Toggle Menu</a>

    <div class="row">
      <div class="col-lg-12">

        <div class="container">
          <div class="row">
            <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
              <%= link_to "Edit Your Profile", edit_user_registration_path %>

              <br>

              <p class=" text-primary"><%= current_user.updated_at.strftime("%B %d, %Y") %> </p>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">


              <div class="panel panel-primary">
                <div class="panel-heading">
                  <h3 class="panel-title light"><i class="ti-id-badge"></i> <%= current_user.name %></h3>
                </div>
                <div class="panel-body border-panel-bod">
                  <div class="row">
                    <div class="col-md-3 col-lg-3 " align="center">

                      <%= image_tag current_user.profileimg.url(:medium), class: "img-circle img-size-profile" %>
                    </div>

                    <!--<div class="col-xs-10 col-sm-10 hidden-md hidden-lg"> <br>
                      <dl>
                        <dt>DEPARTMENT:</dt>
                        <dd>Administrator</dd>
                        <dt>HIRE DATE</dt>
                        <dd>11/12/2013</dd>
                        <dt>DATE OF BIRTH</dt>
                           <dd>11/12/2013</dd>
                        <dt>GENDER</dt>
                        <dd>Male</dd>
                      </dl>
                    </div>-->
                    <div class=" col-md-9 col-lg-9 ">
                      <table class="table table-user-information">
                        <tbody>
                        <tr>
                          <td class="growth-p">Name:</td>
                          <td class="growth-p"><%= current_user.name %></td>
                        </tr>
                        <tr>
                          <td class="growth-p">Company Name</td>
                          <td class="growth-p"><%= is_company_empty(current_user.company) %></td>
                        </tr>
                        <tr>
                          <td class="growth-p">Email</td>
                          <td class="growth-p"><%= current_user.email %></td>
                        </tr>


                        </tbody>
                      </table>

                      <%= link_to projects_path, class: "btn btn-info btn-rounded btn-fill" do %>
                          <i class="ti-folder"></i> Consult Project
                      <% end %>
                      <%= link_to edit_user_registration_path, class: "btn btn-success btn-fill btn-rounded" do %>
                          <i class="ti-user"></i> Edit Your Profile
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="panel-footer padding-footer-prof back-panel-prof">

                </div>

              </div>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>
</div>