config/routes.rb
Rails.application.routes.draw do



  get 'devices/responsive'

  resources :categories


  resources :websites do
    collection do
      get 'search'
    end
    resources :orders, only: [:new, :create] do
      collection do
        get 'search'
      end
    end
  end


  resources :projects do
    collection do
      get 'search'
    end
    resources :reviews
  end



  get 'info/why_us'
  get 'info/pricing'
  get 'info/portofolio'


  resources :blogs do
    collection do
      get 'search'
    end
  end



  get 'users/index'

  get 'search' => "users#search"



  get 'users/show'

  devise_for :users



  match 'user_root' => 'users#show', via: [:get]
  match "profile" => "users#show", :as => 'profile', via: [:get]
  match 'users/:id' => 'users#destroy', :via => :delete, as: :admin_destroy_user

  root "pages#home"

#   =======================ERRORS=======================
  %w( 404 422 500 ).each do |code|
    get code, :to => "pages#show", :code => code
  end

#   =======================ERRORS END ==================

  get 'seller' => "websites#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'all_orders' => "orders#all_order"

  get 'how_does_it_work' => "info#how_does_it_work"

  get 'what_can_i_do' => "info#what_can_i_do"



end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :reviews

  searchkick
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_user_and_manager, except: [:index,:show]

  layout "admin"

  def search
    if params[:search].present?
      @projects = Project.search(params[:search])
    else
      @projects = Project.all.order("created_at DESC")
    end
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @reviews = Review.where(project_id: @project.id).order("created_at DESC")
  end

  # GET /projects/new
  def new
    @project = Project.new
    @users = User.all
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save

        # Deliver the confirmation
        UserNotifier.send_confirmation_project_email(@project.user).deliver

        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
      unless (current_user == @project.user) || (current_user.manager?)
        redirect_to root_url, alert: "Sorry, you can not access here, it not belong to you"
      end

    end

  def check_user_and_manager
    unless current_user.manager?
      redirect_to root_url, alert: "Sorry only manager can do that"
    end
  end


    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title,:user_id, :description, :progress, :link)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def is_link_available(link)
    if link.blank?
      "a link will be provide soon"
    end
  end

  def is_admin_or_client(user)
    if user.admin?
      "Web Developer"
    elsif user.manager?
      "Product Manager"
    elsif user
      "Client"
    else
      "error this person should not be here please alert us"

    end
  end

  def put_color_admin_or_client(user)
    if user.admin?
      "label-primary"
    elsif user.manager?
      "label-info"
    elsif user
      "label-success"
    else
      "label-alert"

    end
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation" class="red">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
    <div class="form-group">
      <%= f.label :user_id %><br>
      <%= f.collection_select :user_id,User.all,:id,:name,{prompt: "Choose a User"},{class: "btn btn-default dropdown-toggle"} %>
    </div>

  <div class="form-group">
    <%= f.label :progress %><br>
    <%= f.number_field :progress, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :link %><br>
    <%= f.url_field :link, class: "form-control" %>
  </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
  <div class="actions">
    <%= f.submit class:"btn btn-default" %>
  </div>
  <br>
<% end %>

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">

<h1 class="thin">Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/projects/index.html.erb
<% if user_signed_in? && current_user.manager? %>

    <!--form search beginning-->
    <%= form_tag search_projects_path, method: :get do %>
        <br>
        <div class="row">
          <div class="col-md-10">
            <%= text_field_tag :search, params[:search], class: "form-control" %>
          </div>
          <div class="col-md-2">
            <%= submit_tag "Search", name: nil, class: "btn btn-info btn-lg" %>
          </div>
        </div>

    <% end %>
<% end %>

<!--form search-->


  <!-- Page Content -->
  <div id="page-content-wrapper">
    <div class="container-fluid">

          <a href="#menu-toggle" class="btn btn-success btn-rounded" id="menu-toggle">Toggle Menu</a>

        <!--===============================================add of project=======================================-->

      <% if user_signed_in? && current_user.manager? %>
          <br>
          <br>

          <div class="row">
            <div class="col-md-10"></div>
            <div class="col-md-2">
              <%= link_to new_project_path do %>
                  <i class="ti-plus size-ic-new-blog"></i>
              <% end %>
            </div>
          </div>
          <br>
          <br>
      <% end %>



        <h1 class="thin center">Listing projects</h1>

        <table class="table table-striped table-hover table-bordered">
          <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Progress</th>
            <th>Link</th>
            <th>User</th>
            <th>Id project</th>
            <th>Write reviews</th>

            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <!--========================security============================-->

          <% @projects.each do |project| %>
              <% if user_signed_in? %>
                  <% if (project.user == current_user) || (current_user.manager?) %>

                      <!--========================security============================-->

                      <tr>
                        <td><%= project.title %></td>
                        <td><%= truncate(project.description,length: 22) %></td>
                        <td><%= number_to_percentage(project.progress,precision: 0) %>
                          <progress class="progress" value="<%= project.progress %>" max="100">
                            <%= number_to_percentage(project.progress) %>
                          </progress>
                        </td>
                        <td><%= link_to is_link_available(project.link),project.link,class: "text-info" %></td>
                        <td><%= project.user.name %></td>
                        <td><%= project.id %></td>
                        <td><%= link_to new_project_review_path(project), class:"text-primary" do %>
                                    Question Click <i class="ti-help-alt"></i>
                            <% end %>
                        </td>
                        <td><%= link_to project, class: "text-success" do %>
                            consult <i class="ti-eye"></i>
                            <% end %>
                        </td>
                        <% if user_signed_in? && current_user.manager? %>
                            <td><%= link_to edit_project_path(project), class: "text-warning" do %>
                                 Edit Project<i class="ti-write"></i>
                            <% end %>
                            </td>
                            <td><%= link_to project, method: :delete, data: {confirm: 'Are you sure?'}, class: "text-danger" do%>
                                    <i class="ti-trash"></i> Destroy
                            <% end %>
                            </td>
                        <% end %>


                      </tr>
                  <% end %>
              <% end %>

          <% end %>
          </tbody>
        </table>

        <br>
    <% if user_signed_in? && current_user.manager? %>
        <%= link_to 'New Project', new_project_path %>
    <% end %>

        <!--===============================================end of project=======================================-->
      </div>
    </div>
  </div>
  <!-- /#page-content-wrapper -->

app/views/projects/new.html.erb
<% @users.each do |user| %>
    <% provide(:user_name, "#{user.name if user == current_user}") %>
<% end %>


<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">

<h1 class="thin">New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/projects/search.html.erb
<!-- Page Content -->
<div id="page-content-wrapper">
  <div class="container-fluid">

    <a href="#menu-toggle" class="btn btn-success btn-rounded" id="menu-toggle">Toggle Menu</a>

    <!--===============================================add of project=======================================-->

    <% if user_signed_in? && current_user.manager? %>
        <br>
        <br>

        <div class="row">
          <div class="col-md-10"></div>
          <div class="col-md-2">
            <%= link_to new_project_path do %>
                <i class="ti-plus size-ic-new-blog"></i>
            <% end %>
          </div>
        </div>
        <br>
        <br>
    <% end %>



    <h1 class="thin center">Listing projects</h1>

    <table class="table table-striped table-hover table-bordered">
      <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Progress</th>
        <th>Link</th>
        <th>User</th>
        <th>Id project</th>
        <th>Write reviews</th>

        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <!--========================security============================-->

      <% @projects.each do |project| %>
          <% if user_signed_in? %>
              <% if (project.user == current_user) || (current_user.manager?) %>

                  <!--========================security============================-->

                  <tr>
                    <td><%= project.title %></td>
                    <td><%= truncate(project.description,length: 22) %></td>
                    <td><%= number_to_percentage(project.progress,precision: 0) %>
                      <progress class="progress" value="<%= project.progress %>" max="100">
                        <%= number_to_percentage(project.progress) %>
                      </progress>
                    </td>
                    <td><%= link_to is_link_available(project.link),project.link,class: "text-info" %></td>
                    <td><%= project.user.name %></td>
                    <td><%= project.id %></td>
                    <td><%= link_to new_project_review_path(project), class:"text-primary" do %>
                          Question Click <i class="ti-help-alt"></i>
                      <% end %>
                    </td>
                    <td><%= link_to project, class: "text-success" do %>
                          consult <i class="ti-eye"></i>
                      <% end %>
                    </td>
                    <% if user_signed_in? && current_user.manager? %>
                        <td><%= link_to edit_project_path(project), class: "text-warning" do %>
                              Edit Project<i class="ti-write"></i>
                          <% end %>
                        </td>
                        <td><%= link_to project, method: :delete, data: {confirm: 'Are you sure?'}, class: "text-danger" do%>
                              <i class="ti-trash"></i> Destroy
                          <% end %>
                        </td>
                    <% end %>


                  </tr>
              <% end %>
          <% end %>

      <% end %>
      </tbody>
    </table>

    <br>
    <% if user_signed_in? && current_user.manager? %>
        <%= link_to 'New Project', new_project_path %>
    <% end %>

    <!--===============================================end of project=======================================-->
  </div>
</div>
</div>
<!-- /#page-content-wrapper -->

app/views/projects/show.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">

    <p id="notice"><%= notice %></p>

    <div class="row">
      <div class="col-md-3">
        <a href="#menu-toggle" class="btn btn-success btn-rounded" id="menu-toggle">Toggle Menu</a>
      </div>
      <div class="col-md-9">
        
        <h4>
          <h1>hello</h1>
          <%= link_to projects_path, class: "text-info" do %>
              <i class="ti-arrow-left"></i>
              <span class="light">Go Back To Project List</span>
          <% end %>
        </h4>
      </div>
    </div>

    <div class="card">
      <div class="content">
        <h1 class="thin"><strong class="color-title">Project Title:</strong>
          <span class="color-title-growth"><%= @project.title %></span></h1>

        <p>
          <strong>Description:</strong>
          <%= @project.description %>
        </p>

        <p>
          <strong>Progress:</strong>
          <%= number_to_percentage(@project.progress, precision: 0) %>
          <progress class="progress style-pro" value="<%= @project.progress %>" max="100">
            25%
          </progress>
        </p>

        <p>
          <strong>Link:</strong>
          <%= link_to is_link_available(@project.link),@project.link%>
        </p>
        <a href="#">
        </a>

        <div class="footer">
          <div class="author">
            <a href="#">
              <img src="<%= @project.user.profileimg.url %>" alt="profile user" class="avatar">
              <span> <%= @project.user.name %> </span>
            </a>
          </div>
          <div class="stats pull-right">
            <i class="fa fa-clock-o"></i> Created
            <%= time_ago_in_words(@project.created_at) %> ago
          </div>
        </div>
      </div>
    </div>

    <% if @reviews.blank? %>
        <h3>No reviews writed</h3>

        <%= link_to 'Back Project', projects_path %>
    <% else %>


        <div class="row">
          <div class="col-md-10"></div>
          <div class="col-md-2">
            <%= link_to new_project_review_path(@project),
                        class: "btn btn-round btn-fill btn-google" do %>
                <i class="ti-pencil-alt write-quest-pro-ic-size"></i>
            <% end %>
          </div>
        </div>


<% @reviews.each do |review| %>
    <div class="media">
      <a class="pull-left" href="#">
        <div class="avatar">
          <img class="media-object" alt="Tim Picture" src="<%= review.user.profileimg.url %>">
        </div>
      </a>

      <div class="media-body">

        <h4 class="media-heading"><%= review.user.name.capitalize %>
          <span class="label <%= put_color_admin_or_client(review.user) %>">
            <%= is_admin_or_client(review.user) %></span></h4>
        <h6 class="pull-right text-muted"><time><%= review.created_at.strftime("%-m/%-d/%y") %></time></h6>

        <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>



        <div class="media-footer">
          <i class="fa fa-reply text-info"></i> <%= link_to "Reply", new_project_review_path(@project) %>
          <a href="#" class="btn btn-default btn-simple pull-right">
            <% if user_signed_in? && current_user.manager? %>
                <%= link_to "Edit Review", edit_project_review_path(@project, review) %>
                <%= link_to "Delete", project_review_path(@project, review), method: :delete,
                            data: {confirm: "Are you sure you want delete this review (#{review.comment})"} %>
            <% end %>
          </a>
        </div>
      </div>
    </div>
<% end %>
    </br>

    <% if user_signed_in? && current_user.manager? %>
        <%= link_to 'Edit Project', edit_project_path(@project) %> |
    <% end %>
        <%= link_to 'Back Project', projects_path %>
  </div>
</div>


<% end %>