config/routes.rb
Rails.application.routes.draw do



  get 'devices/responsive'

  resources :categories


  resources :websites do
    collection do
      get 'search'
    end
    resources :orders, only: [:new, :create] do
      collection do
        get 'search'
      end
    end
  end


  resources :projects do
    collection do
      get 'search'
    end
    resources :reviews
  end



  get 'info/why_us'
  get 'info/pricing'
  get 'info/portofolio'


  resources :blogs do
    collection do
      get 'search'
    end
  end



  get 'users/index'

  get 'search' => "users#search"



  get 'users/show'

  devise_for :users



  match 'user_root' => 'users#show', via: [:get]
  match "profile" => "users#show", :as => 'profile', via: [:get]
  match 'users/:id' => 'users#destroy', :via => :delete, as: :admin_destroy_user

  root "pages#home"

#   =======================ERRORS=======================
  %w( 404 422 500 ).each do |code|
    get code, :to => "pages#show", :code => code
  end

#   =======================ERRORS END ==================

  get 'seller' => "websites#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'all_orders' => "orders#all_order"

  get 'how_does_it_work' => "info#how_does_it_work"

  get 'what_can_i_do' => "info#what_can_i_do"



end

app/views/layouts/_admin_header.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand margin-name">
      <a href="#">


        <p><%= image_tag current_user.profileimg.url(:medium), class: "image-profile margin-profile img-circle border-profile" %></p>


        <p class="center name"><%= link_to current_user.name, profile_path %></p>


        <!--link_to "#{yield(:user_name)}",profile_path -->

      </a>
    </li>
    <% if user_signed_in? %>
    <li>
      <%= link_to what_can_i_do_path do %>
          <i class="ti-help-alt style-sign-out-ic"></i>
          <span class="margin-right-menu-admin"  data-toggle="tooltip" data-placement="right" title="A List Of Activity That You Can Do">What Can I do</span>
      <% end %>
    </li>
    <% end %>
    <% if user_signed_in? && current_user.manager? %>
        <li>
          <%= link_to all_orders_path do %>
              <i class="ti-credit-card style-sign-out-ic"></i>
              <span class="margin-right-menu-admin" data-placement="right" title="Consult All Orders">All Orders</span>
          <% end %>
        </li>
    <% end %>

    <% if user_signed_in? && current_user.manager? %>
        <li>
          <%= link_to users_index_path do %>
            <i class="ti-info-alt style-sign-out-ic"></i>
            <span class="margin-right-menu-admin" data-placement="right" title="All User Informations">User Info</span>
          <% end %>
        </li>
    <% end %>

    <% if user_signed_in? && current_user.admin? %>
        <li>
          <%= link_to sales_path do%>
            <i class="ti-receipt style-sign-out-ic"></i>
            <span class="margin-right-menu-admin" data-placement="right" title="Your Sales Listed">Sales History</span>
          <% end %>
        </li>
    <% end %>

    <li>
      <%= link_to purchases_path do %>
         <i class="ti-shopping-cart-full style-sign-out-ic"></i>
          <span class="margin-right-menu-admin" data-placement="right" title="Consult Your Past Purchased">Purchase History</span>
      <% end %>
    </li>
    <li>
      <%= link_to profile_path do %>
          <i class="ti-user style-sign-out-ic"></i>
          <span class="margin-right-menu-admin" data-placement="right" title="You Can Edit Your Account Here">Edit Profile</span>
      <% end %>
    </li>
    <% if user_signed_in? %>
    <li>
        <li><%= link_to projects_path do %>
          <i class="ti-folder style-sign-out-ic"></i>
          <span class="margin-right-menu-admin" data-placement="right"
                title="Once Your Project Created You can have access to his progress here">Projects</span>
        <% end %>
        </li>
    </li>
    <% end %>
    <li>
      <a href="#">Contact</a>
    </li>
    <li>
      <%= link_to "home", root_path %>
    </li>
    <li class="margin-top-sign-out">
      <%= link_to destroy_user_session_path, method: :delete do %>
           <i class="ti-unlock style-sign-out-ic"></i>
           <span class="margin-right-menu-admin">Sign Out</span>
      <% end %>
    </li>

  </ul>
</div>
<!-- /#sidebar-wrapper -->

app/views/layouts/_device_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <i class="fa fa-sign-in fa-2x asowesome-color"></i>
        </button>




      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li>
              <%= link_to websites_path do %>

                  <i class="ti-arrow-circle-left navbar-form navbar-left device-margin-left color-device-goback"></i>

              <% end %>

            </li>

            <li>
              <a id="myDevice1" href="javascript:showonedevice('device1');" >
                 <i class="ti-desktop navbar-form navbar-left device-margin-left color-device-desktop"></i>
              </a>
            </li>
            <li>
              <a id="myDevice2" href="javascript:showonedevice('device2');" >
                 <i class="ti-tablet navbar-form navbar-left device-margin-left color-device-tablet"></i>
              </a>
            </li>
            <li>
               <a id="myDevice3" href="javascript:showonedevice('device3');" >
                  <i class="ti-mobile navbar-form navbar-left device-margin-left color-device-mobile"></i>
               </a>
            </li>

        </ul>


        <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Order it Now", new_website_order_path(@website),
                     class: "btn btn-primary btn-round device-fonts-color light", data: { no_turbolink: true } %></li>

        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </div>
</nav>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>

    <p class="alert alert-success light flash-center helvetica">
      <%= notice %> <i class="ti-check ic-flash"></i>
    </p>

<% end %>

<% if flash[:alert] %>

    <p class="alert alert-danger alert-dismissible light flash-center helvetica">
      <%= alert %> <i class="ti-alert"></i>
    </p>

<% end %>

app/views/layouts/_footer.html.erb
<div class="separator"></div>
<div class="social-line <%= yield(:visibility_thank_for_sharing).presence || 'hidden' %> background-share">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h4 class="title light">Thank you for sharing!</h4>
      </div>
      <div class="col-md-2">
        <a href="" class="btn btn-round btn-fill btn-facebook">
          <i class="fa fa-facebook-square"></i> Share &middot; 753
        </a>
      </div>
      <div class="col-md-2">
        <a href="" class="btn btn-round btn-fill btn-twitter">
          <i class="fa fa-twitter"></i> Tweet &middot; 832
        </a>
      </div>
      <div class="col-md-2">
        <a href="" class="btn btn-round btn-fill btn-google">
          <i class="fa fa-google-plus-square"></i> Share &middot; 131
        </a>
      </div>
      <div class="col-md-2">
        <a href="" class="btn btn-round btn-fill btn-youtube">
          <i class="fa fa-pinterest"></i> Pin it &middot; 323
        </a>
      </div>
    </div>
  </div>
</div>
<br>




<div class="social-line <%= yield(:footer_visibility).presence || 'hidden'%>
<%= yield(:visibility_social_share) %> background-share" id="sharing">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h4 class="title light">We are social:</h4>
      </div>
      <div class="col-md-2">
        <button class="btn btn-social btn-simple btn-facebook">
          <i class="fa fa-facebook-square border-right-none"></i> Facebook
        </button>
      </div>
      <div class="col-md-2">
        <button class="btn btn-social btn-simple btn-twitter">
          <i class="fa fa-twitter border-right-none"></i> Twitter
        </button>
      </div>
      <div class="col-md-2">
        <button class="btn btn-social btn-simple btn-google">
          <i class="fa fa-google-plus-square border-right-none"></i> Google+
        </button>
      </div>
      <div class="col-md-2">
        <button class="btn btn-social btn-simple btn-linkedin">
          <i class="fa fa-linkedin-square border-right-none"></i> Linkedin
        </button>
      </div>
    </div>
  </div>
</div>




<footer class="<%= yield(:background_footer).presence || 'background-our-footer-info' %>
<%= yield(:footer_visibility).presence || 'hidden'%>">

  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 margin-our-team center">
      <% if user_signed_in? %>
          <h1 class="thin <%= yield(:provide_white)%> margin-p-shop margin-button">
            CLICK AT THE BOTTOM TO GO TO YOUR ACCOUNT</h1>
          <%= link_to "#", class: "btn btn-info btn-outline btn-rounded btn-lg" do %>
              <b>GO TO MY ACCOUNT</b>
          <% end %>
      <% else %>
      <h1 class="thin <%= yield(:provide_white)%> margin-p-shop margin-button">CREATE AN ACCOUNT</h1>
      <%= link_to "#", class: "btn btn-info btn-outline btn-rounded btn-lg" do %>
          <b>GET STARTED - TODAY!</b>
      <% end %>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>


  <div class="row">
    <div class="col-md-3 center border-right-footer">
      <i class="ti-shopping-cart <%= yield(:provide_white)%> shop-footer-size"></i>
      <h5 class="<%= yield(:provide_white)%> light">Order your next website</h5>
    </div>
    <div class="col-md-3 center border-right-footer">
      <i class="ti-headphone-alt <%= yield(:provide_white)%> shop-footer-size"></i>
      <h5 class="<%= yield(:provide_white)%> light"> Our Support Center Click Here</h5>

    </div>
    <div class="col-md-3 center border-right-footer">
      <i class="ti-comment <%= yield(:provide_white)%> shop-footer-size"></i>
      <h5 class="<%= yield(:provide_white)%> light">We contentsly blog visit our blog</h5>
    </div>
    <div class="col-md-3 center">
      <i class="ti-help <%= yield(:provide_white)%> shop-footer-size"></i>
      <h5 class="<%= yield(:provide_white)%> light"> Need help? you can contact us 414-4393-4839</h5>
    </div>
  </div>
</footer>

app/views/layouts/_footer_shit.html.erb
<footer class="footer footer-big <%= yield(:visibility_footer_shit) %>">
  <!-- .footer-black is another class for the footer, for the transparent version, we recommend you to change the url of the image with your favourite image.          -->

  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <div class="form-group">
          <!-- Single button -->
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
              <%= image_tag("ca.png") %> English <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#"><%= image_tag("ca.png") %> French
                <span class="label label-default">soon</span></a></li>
              <li><a href="#"><%= image_tag("es.png") %> Spanish
                <span class="label label-default">soon</span></a></li>

            </ul>
          </div>
        </div>

        <div class="form-group">
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
              <%= image_tag("ca.png") %> CAD <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#"><%= image_tag("us.png") %> US
                <span class="label label-default">soon</span></a></li>

            </ul>
          </div>
        </div>

      </div>
      <div class="col-md-3 col-md-offset-1">
        <h5 class="title">Company</h5>
        <nav>
          <ul>
            <li>
              <a href="#">
                Home
              </a>
            </li>
            <li>
              <a href="#">
                Find offers <span class="label label-info">soon</span>
              </a>
            </li>
            <li>
              <a href="#">
                Portfolio
              </a>
            </li>
            <li>
              <a href="#">
                Our news
              </a>
            </li>
            <li>
              <a href="#">
                About Us
              </a>
            </li>
          </ul>
        </nav>
      </div>
      <div class="col-md-3">
        <h5 class="title"> Help and Support</h5>
        <nav>
          <ul>
            <li>
              <a href="#">
                Contact Us
              </a>
            </li>
            <li>
              <a href="#">
                How it works
              </a>
            </li>
            <li>
              <a href="#">
                Terms &amp; Conditions  <span class="label label-info">soon</span>
              </a>
            </li>
            <li>
              <a href="#">
                Company Policy <span class="label label-info">soon</span>
              </a>
            </li>
          </ul>
        </nav>
      </div>
      <div class="col-md-3">
        <h5 class="title">Follow us on</h5>
        <nav>
          <ul>
            <li>
              <button class="btn btn-social btn-simple btn-facebook">
                <i class="fa fa-facebook-square border-right-none"></i> Facebook
              </button>
            </li>
            <li>
              <button class="btn btn-social btn-simple btn-twitter">
                <i class="fa fa-twitter border-right-none"></i> Twitter
              </button>
            </li>
            <li>
              <button class="btn btn-social btn-simple btn-linkedin">
                <i class="fa fa-linkedin-square border-right-none"></i> Linkedin
              </button>
            <li>
              <button class="btn btn-social btn-simple btn-google">
                <i class="fa fa-google-plus-square border-right-none"></i> Google+
              </button>
            </li>

          </ul>
        </nav>
      </div>
    </div>
    <hr>
    <div class="copyright">
      © 2014 Webee, Web Development and Design Agency
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <i class="ti-unlock asowesome-color login-padlock-size"></i>
        </button>

        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle navbar-brand color-title" data-toggle="dropdown">
              <i class="ti-align-justify"></i> <span class="light">Webee</span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li>
              <li class="center style-x"><i class="ti-close border-cross-menu pink"></i></li>
              <li><%= link_to "home", root_path, class: "hover-home size-menu light" %></li>
              <li class="divider"></li>
              <li><%= link_to "How Does It Work", how_does_it_work_path, class: "hover-how-it-works size-menu light" %></li>
              <li class="divider"></li>
              <li><%= link_to "portofolio", info_portofolio_path, class: "hover-portofolio size-menu light" %></li>
              <li class="divider"></li>
              <li><%= link_to "Pricing", info_pricing_path, class: "hover-pricing size-menu light" %></li>
              <li class="divider"></li>
              <li><%= link_to "why us", info_why_us_path, class: "hover-why-us size-menu light" %>
              <li class="divider"></li>
              <li><%= link_to "blog", blogs_path %></li>

              <% if user_signed_in? && current_user.manager? %>
                  <li class="divider"></li>
                  <li><%= link_to "user info", users_index_path %></li>
              <% end %>

              <% if user_signed_in? %>
                  <li class="divider"></li>
                  <li><%= link_to "project", projects_path %></li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to "website", websites_path %></li>

              <% if user_signed_in? && current_user.admin? %>
                  <li class="divider"></li>
                  <li><%= link_to "manage website", seller_path %></li>
              <% end %>
              <li class="divider"></li>
              <li class="center ic-menu-size"><i class="ti-twitter text-info"></i>
                  <i class="ti-facebook text-primary"></i>
                  <i class="ti-google text-danger"></i>
                  <i class="ti-linkedin color-linkedin-ic"></i>
              </li>


            </ul>
          </li>
        </ul>

        <!--=======================here=================-->

        <!--form search beginning-->
        <%= form_tag search_blogs_path, class: "navbar-form navbar-right margin-form
        #{yield(:visibility_search_blog).presence || 'hidden'}", method: :get do %>
            <p>
              <%= text_field_tag :search, params[:search], placeholder: "Search", class: "field__input" %>

            </p>
        <% end %>

        <!--form search-->


        <!--======end=================-->

        <!--=======================here=================-->

        <!--form search beginning-->
        <%= form_tag search_websites_path, class: "navbar-form navbar-right margin-form
         #{yield(:visibility_search_website).presence || 'hidden'}", method: :get do %>
            <p>
              <%= text_field_tag :search, params[:search], placeholder: "Search", class: "field__input" %>

            </p>
        <% end %>

        <!--form search-->

        <!--======end=================-->

        <!--=======================here=================-->

        <form class="navbar-form navbar-right margin-form hidden" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>

        <!--======end=================-->


      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <div class="btn-group margin-browse-button <%= yield(:browse_website_visibility).presence || 'hidden' %>">
          <button type="button" class="btn btn-info">Browse by Field</button>
          <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>

                <li><%= link_to category.name, websites_path(category: category.name) %></li>
            <% end %>


          </ul>
        </div>

        <%= link_to blogs_path,
                    class: "margin-menu-back navbar-nav text-primary
                light #{yield(:go_back_blog_visibility).presence || 'hidden'}" do %>
            <i class="ti-arrow-circle-left"></i> Go Back To Blogs

        <% end %>

        <%= link_to profile_path,
                    class: "margin-menu-back navbar-nav text-primary
                light #{yield(:go_back_profile_visibility).presence || 'hidden'}" do %>
            <i class="ti-arrow-circle-left"></i> Go Back To My Profile

        <% end %>


        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary btn-outline btn-rounded light border-color-degr btn-lg" %></li>
          <% else %>
              <li><%= link_to "Sign in", new_user_session_path, class: "btn btn-primary btn-outline btn-rounded light border-color-degr btn-lg" %></li>
          <% end %>

        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </div>
</nav>

app/views/layouts/_info_header.html.erb
<div class="<%= yield(:background) %>">
  <nav class="navbar navbar-default back-bord-remove" role="navigation">
    <div class="container back-bord-remove">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <i class="ti-unlock <%= yield(:toggle_nav) %> login-padlock-size"></i>
          </button>

          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle navbar-brand color-title" data-toggle="dropdown">
                <i class="ti-align-justify <%= yield(:bars) %>"></i>
                <span class="<%= yield(:bars) %> <%= yield(:visibility_brand_info) %>">Webee</span>
              </a>
              <ul class="dropdown-menu background-white" role="menu">
                <li class="center style-x">
                  <i class="ti-close <%= yield(:border_cross_menu_color) %> <%= yield(:icon_color) %>"></i></li>
                <li><%= link_to "home", root_path, class: "hover-home size-menu light" %></li>
                <li class="divider"></li>
                <li><%= link_to "How Does It Work", how_does_it_work_path, class: "hover-how-it-works size-menu light" %></li>
                <li class="divider"></li>
                <li><%= link_to "portofolio", info_portofolio_path, class: "hover-portofolio size-menu light" %></li>
                <li class="divider"></li>
                <li><%= link_to "Pricing", info_pricing_path, class: "hover-pricing size-menu light" %></li>
                <li class="divider"></li>
                <li><%= link_to "why us", info_why_us_path, class: "hover-why-us size-menu light" %>
                <li class="divider"></li>
                <li><%= link_to "blog", blogs_path %></li>
                <li class="divider"></li>
                <li><%= link_to "website", websites_path %></li>
                <% if user_signed_in? && current_user.manager? %>
                    <li class="divider"></li>
                    <li><%= link_to "user info", users_index_path %></li>
                <% end %>
                <li class="divider"></li>
                <li class="center ic-menu-size"><i class="ti-twitter text-info"></i>
                  <i class="ti-facebook text-primary"></i>
                  <i class="ti-google text-danger"></i>
                  <i class="ti-linkedin color-linkedin-ic"></i>
                </li>


              </ul>
            </li>
          </ul>


        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary btn-outline btn-rounded light #{yield(:signout)}" %></li>
            <% else %>
                <li><%= link_to "Sign in", new_user_session_path, class: "btn btn-primary btn-outline btn-rounded light #{yield(:signin)}" %></li>
            <% end %>

          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </div>
  </nav>
</div>

app/views/layouts/_menu_info.html.erb
<div class="background-why-us">
  <nav class="navbar navbar-default back-bord-remove" role="navigation">
    <div class="container">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <i class="fa fa-sign-in fa-2x white"></i>
          </button>

          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle navbar-brand color-title" data-toggle="dropdown">
                <i class="fa fa-bars white"></i>
              </a>
              <ul class="dropdown-menu background-white" role="menu">
                <li class="center style-x"><i class="fi-x purple"></i></li>
                <li><%= link_to "home", root_path, class: "hover-home" %></li>
                <li class="divider"></li>
                <li><a href="#">Portofolio</a></li>
                <li class="divider"></li>
                <li><a href="#">Pricing</a></li>
                <li class="divider"></li>
                <li><%= link_to "why us", info_why_us_path, class: "hover-why-us" %>
                <li class="divider"></li>
                <li><%= link_to "blog", blogs_path %></li>
                <li class="divider"></li>
                <li><%= link_to "user info", users_index_path %></li>
                <li class="divider"></li>
                <li><%= link_to "edit user", edit_user_registration_path %></li>


              </ul>
            </li>
          </ul>


        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary light white" %></li>
            <% else %>
                <li><%= link_to "Sign in", new_user_session_path, class: "btn btn-primary light white" %></li>
            <% end %>

          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </div>
  </nav>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Webee</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= javascript_include_tag :modernizr %>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body class="admin-top <%= yield(:background_admin) %>">
<%= render 'layouts/flash' %>

<div id="wrapper">
  <%= render 'layouts/admin_header' %>

<%= yield %>

</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= yield(:title_page) %></title>
  <meta name="description" content="<%= yield(:meta_description) %>">
  <meta name="author" content="<%= yield(:author) %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= tag :meta, :name => "stripe-key", :content => Figaro.env.STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= yield(:background_color_blog) %>">
  <%= render 'layouts/flash' %>
  <%= render 'layouts/header' %>


  <%= yield %>
  <%= render 'layouts/footer_shit' %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/device.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Webee - <%= yield(:title_page) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
  <%= csrf_meta_tags %>
</head>
<body class="padding-device">
<%= render 'layouts/flash' %>
<%= render 'layouts/device_header' %>


<%= yield %>

</body>
</html>

app/views/layouts/info.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Webee - <%= yield(:title_page) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
  <%= csrf_meta_tags %>
</head>
<body class="info-boby">

<%= render 'layouts/flash' %>
<%= render 'layouts/info_header' %>



<%= yield %>


<%= render 'layouts/footer' %>
</body>
</html>